// Date: 8/21/2012 9:42:44 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX




// Date: 12/18/2012 10:05:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelshit extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape21;
    ModelRenderer Shape211;
    ModelRenderer Shape211111111111;
    ModelRenderer Shape41;
    ModelRenderer Shape2111111111;
    ModelRenderer Shape51;
    ModelRenderer Shape21111111111;
    ModelRenderer Shape5;
    ModelRenderer Shape511111111111;
    ModelRenderer Shape5111111111111;
    ModelRenderer Shape4;
    ModelRenderer Shape51111111111;
    ModelRenderer Shape5111111111;
    ModelRenderer Shape511111111;
    ModelRenderer Shape51111111;
    ModelRenderer Shape41111111;
    ModelRenderer Shape5111111;
    ModelRenderer Shape511111;
    ModelRenderer Shape51111;
    ModelRenderer Shape5111;
    ModelRenderer Shape4111111;
    ModelRenderer Shape511;
    ModelRenderer Shape411111;
    ModelRenderer Shape311111;
    ModelRenderer Shape41111;
    ModelRenderer Shape4111;
    ModelRenderer Shape211111111;
    ModelRenderer Shape21111111;
    ModelRenderer Shape211111;
    ModelRenderer Shape2111111;
    ModelRenderer Shape21111;
    ModelRenderer Shape2111;
    ModelRenderer Shape411;
    ModelRenderer Shape61111;
    ModelRenderer Shape6111;
    ModelRenderer Shape611;
    ModelRenderer shapehanndle;
    ModelRenderer Shape6;
    ModelRenderer Shape61;
    ModelRenderer Shape31111;
    ModelRenderer Shape311;
    ModelRenderer Shape31;
    ModelRenderer Shape3111;
  
  public Modelshit()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      Shape1 = new ModelRenderer(this, 0, 239);
      Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
      Shape1.setRotationPoint(-8F, 23F, -8F);
      Shape1.setTextureSize(256, 256);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 206);
      Shape2.addBox(0F, -19F, 0F, 1, 19, 13);
      Shape2.setRotationPoint(-6.5F, 22F, 0.5F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 1.570796F, 0F);
      Shape3 = new ModelRenderer(this, 22, 72);
      Shape3.addBox(-7.5F, 0F, -6.5F, 1, 2, 13);
      Shape3.setRotationPoint(0F, 1.5F, 0.2F);
      Shape3.setTextureSize(256, 256);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 1.570796F, 0F);
      Shape2 = new ModelRenderer(this, 0, 164);
      Shape2.addBox(0F, -21F, 0F, 1, 22, 1);
      Shape2.setRotationPoint(6F, 22F, -7F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 29, 207);
      Shape2.addBox(0F, -18F, 0F, 2, 19, 12);
      Shape2.setRotationPoint(-6F, 21F, 1F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 1.570796F, 0F);
      Shape2 = new ModelRenderer(this, 0, 206);
      Shape2.addBox(0F, -19F, 0F, 1, 19, 13);
      Shape2.setRotationPoint(-0.5F, 22F, -6.5F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape41 = new ModelRenderer(this, 0, 150);
      Shape41.addBox(0F, 0F, 0F, 12, 1, 12);
      Shape41.setRotationPoint(-6F, 3F, -6F);
      Shape41.setTextureSize(256, 256);
      Shape41.mirror = true;
      setRotation(Shape41, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 29, 207);
      Shape2.addBox(0F, -19F, 0F, 2, 19, 12);
      Shape2.setRotationPoint(-1F, 22F, -6F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(0.5F, 10F, -5.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 164);
      Shape2.addBox(0F, -22F, 0F, 1, 22, 1);
      Shape2.setRotationPoint(5.5F, 22.5F, -6.5F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 38, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(0.5F, 10F, -0.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(-5.5F, 10F, -0.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 122);
      Shape51.addBox(0F, 0F, 0F, 11, 6, 11);
      Shape51.setRotationPoint(-5.5F, 3F, -5.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape41 = new ModelRenderer(this, 0, 150);
      Shape41.addBox(0F, 0F, 0F, 12, 1, 12);
      Shape41.setRotationPoint(-6F, 21F, -6F);
      Shape41.setTextureSize(256, 256);
      Shape41.mirror = true;
      setRotation(Shape41, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(-5.5F, 18F, -5.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(0.5F, 18F, -5.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(0.5F, 18F, -0.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(-5.5F, 18F, -0.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape41 = new ModelRenderer(this, 0, 150);
      Shape41.addBox(0F, 0F, 0F, 12, 1, 12);
      Shape41.setRotationPoint(-6F, 17F, -6F);
      Shape41.setTextureSize(256, 256);
      Shape41.mirror = true;
      setRotation(Shape41, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(-5.5F, 14F, -5.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(-5.5F, 14F, -0.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(0.5F, 14F, -0.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(0.5F, 14F, -5.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape41 = new ModelRenderer(this, 0, 150);
      Shape41.addBox(0F, 0F, 0F, 12, 1, 12);
      Shape41.setRotationPoint(-6F, 13F, -6F);
      Shape41.setTextureSize(256, 256);
      Shape41.mirror = true;
      setRotation(Shape41, 0F, 0F, 0F);
      Shape51 = new ModelRenderer(this, 0, 140);
      Shape51.addBox(0F, 0F, 0F, 5, 3, 6);
      Shape51.setRotationPoint(-5.5F, 10F, -5.5F);
      Shape51.setTextureSize(256, 256);
      Shape51.mirror = true;
      setRotation(Shape51, 0F, 0F, 0F);
      Shape41 = new ModelRenderer(this, 0, 111);
      Shape41.addBox(0F, 0F, 0F, 9, 1, 9);
      Shape41.setRotationPoint(-4.5F, -0.5F, -4.5F);
      Shape41.setTextureSize(256, 256);
      Shape41.mirror = true;
      setRotation(Shape41, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 61, 189);
      Shape3.addBox(0F, 0F, 0F, 15, 1, 15);
      Shape3.setRotationPoint(-7.5F, 22F, -7.5F);
      Shape3.setTextureSize(256, 256);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape41 = new ModelRenderer(this, 0, 150);
      Shape41.addBox(0F, 0F, 0F, 12, 1, 12);
      Shape41.setRotationPoint(-6F, 9F, -6F);
      Shape41.setTextureSize(256, 256);
      Shape41.mirror = true;
      setRotation(Shape41, 0F, 0F, 0F);
      Shape41 = new ModelRenderer(this, 122, 191);
      Shape41.addBox(0F, 0F, 0F, 13, 1, 13);
      Shape41.setRotationPoint(-6.5F, 0.5F, -6.5F);
      Shape41.setTextureSize(256, 256);
      Shape41.mirror = true;
      setRotation(Shape41, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 164);
      Shape2.addBox(0F, -21F, 0F, 1, 22, 1);
      Shape2.setRotationPoint(-7F, 22F, -7F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 164);
      Shape2.addBox(0F, -22F, 0F, 1, 22, 1);
      Shape2.setRotationPoint(-6.5F, 22.5F, -6.5F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 164);
      Shape2.addBox(0F, -21F, 0F, 1, 22, 1);
      Shape2.setRotationPoint(6F, 22F, 6F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 164);
      Shape2.addBox(0F, -22F, 0F, 1, 22, 1);
      Shape2.setRotationPoint(5.5F, 22.5F, 5.5F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 164);
      Shape2.addBox(0F, -22F, 0F, 1, 22, 1);
      Shape2.setRotationPoint(-6.5F, 22.5F, 5.5F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 164);
      Shape2.addBox(0F, -21F, 0F, 1, 22, 1);
      Shape2.setRotationPoint(-7F, 22F, 6F);
      Shape2.setTextureSize(256, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape41 = new ModelRenderer(this, 0, 150);
      Shape41.addBox(0F, 0F, 0F, 12, 1, 12);
      Shape41.setRotationPoint(-6F, 0F, -6F);
      Shape41.setTextureSize(256, 256);
      Shape41.mirror = true;
      setRotation(Shape41, 0F, 0F, 0F);
      Shape61111 = new ModelRenderer(this, 0, 106);
      Shape61111.addBox(0F, 0F, 0F, 2, 3, 0);
      Shape61111.setRotationPoint(1F, -3F, -1F);
      Shape61111.setTextureSize(256, 256);
      Shape61111.mirror = true;
      setRotation(Shape61111, 0F, 3.141593F, 0F);
      Shape61111 = new ModelRenderer(this, 0, 102);
      Shape61111.addBox(0F, 0F, 0F, 2, 1, 2);
      Shape61111.setRotationPoint(-1F, -3.3F, 1F);
      Shape61111.setTextureSize(256, 256);
      Shape61111.mirror = true;
      setRotation(Shape61111, 0F, 1.570796F, 0F);
      Shape61111 = new ModelRenderer(this, 0, 106);
      Shape61111.addBox(0F, -2F, 0F, 2, 3, 0);
      Shape61111.setRotationPoint(1F, -1F, 1F);
      Shape61111.setTextureSize(256, 256);
      Shape61111.mirror = true;
      setRotation(Shape61111, 0F, 3.141593F, 0F);
      shapehanndle = new ModelRenderer(this, 6, 106);
      shapehanndle.addBox(0F, 1F, 0F, 2, 3, 0);
      shapehanndle.setRotationPoint(-0.6F, 10.93333F, 7F);
      shapehanndle.setTextureSize(256, 256);
      shapehanndle.mirror = true;
      setRotation(shapehanndle, 0F, 1.570796F, 0F);
      Shape61111 = new ModelRenderer(this, 0, 106);
      Shape61111.addBox(0F, 0F, 0F, 2, 3, 0);
      Shape61111.setRotationPoint(1F, -3F, 1F);
      Shape61111.setTextureSize(256, 256);
      Shape61111.mirror = true;
      setRotation(Shape61111, 0F, 1.570796F, 0F);
      Shape61111 = new ModelRenderer(this, 0, 106);
      Shape61111.addBox(0F, -2F, 0F, 2, 3, 0);
      Shape61111.setRotationPoint(-1F, -1F, 1F);
      Shape61111.setTextureSize(256, 256);
      Shape61111.mirror = true;
      setRotation(Shape61111, 0F, 1.570796F, 0F);
      Shape3 = new ModelRenderer(this, 0, 188);
      Shape3.addBox(0F, 0F, 0F, 15, 2, 15);
      Shape3.setRotationPoint(-7.5F, 1.5F, -7.5F);
      Shape3.setTextureSize(256, 256);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 22, 72);
      Shape3.addBox(-7.5F, 0F, -7.5F, 1, 2, 13);
      Shape3.setRotationPoint(-1F, 1.5F, -0.2F);
      Shape3.setTextureSize(256, 256);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, -1.570796F, 0F);
      Shape3 = new ModelRenderer(this, 22, 72);
      Shape3.addBox(-7.5F, 0F, -7.5F, 1, 2, 13);
      Shape3.setRotationPoint(14.2F, 1.5F, 1F);
      Shape3.setTextureSize(256, 256);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 22, 72);
      Shape3.addBox(-7.5F, 0F, -7.5F, 1, 2, 13);
      Shape3.setRotationPoint(-0.2F, 1.5F, 1F);
      Shape3.setTextureSize(256, 256);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape41.render(f5);
    Shape2.render(f5);
    Shape51.render(f5);
    Shape2.render(f5);
    Shape51.render(f5);
    Shape51.render(f5);
    Shape51.render(f5);
    Shape41.render(f5);
    Shape51.render(f5);
    Shape51.render(f5);
    Shape51.render(f5);
    Shape51.render(f5);
    Shape41.render(f5);
    Shape51.render(f5);
    Shape51.render(f5);
    Shape51.render(f5);
    Shape51.render(f5);
    Shape41.render(f5);
    Shape51.render(f5);
    Shape41.render(f5);
    Shape3.render(f5);
    Shape41.render(f5);
    Shape41.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape41.render(f5);
    Shape61111.render(f5);
    Shape61111.render(f5);
    Shape61111.render(f5);
    shapehanndle.render(f5);
    Shape61111.render(f5);
    Shape61111.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

public void renderModel(float f) {
	// TODO Auto-generated method stub
	
}

}