// Date: 8/5/2012 6:29:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelpancakezombie extends ModelBase
{
    ModelRenderer torso;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer torso2;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
  
  public Modelpancakezombie()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      torso = new ModelRenderer(this, 0, 0);
      torso.addBox(-3F, -6F, 0F, 8, 8, 1);
      torso.setRotationPoint(-1F, 20F, -1F);
      torso.setTextureSize(64, 32);
      torso.mirror = true;
      setRotation(torso, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 19, 0);
      leg1.addBox(0F, 0F, 0F, 1, 2, 1);
      leg1.setRotationPoint(-2F, 22F, -1F);
      leg1.setTextureSize(64, 32);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 24, 0);
      leg2.addBox(0F, 0F, 0F, 1, 2, 1);
      leg2.setRotationPoint(1F, 22F, -1F);
      leg2.setTextureSize(64, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 10);
      torso2.addBox(-2F, -2F, -1F, 6, 6, 1);
      torso2.setRotationPoint(-1.033333F, 17F, -0.2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 18);
      Shape1.addBox(0F, 0F, 0F, 1, 0, 1);
      Shape1.setRotationPoint(-4F, 17F, -1F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 20);
      Shape2.addBox(0F, 0F, 0F, 0, 1, 1);
      Shape2.setRotationPoint(-3F, 16F, -1F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 18);
      Shape3.addBox(0F, -1F, 0F, 1, 0, 1);
      Shape3.setRotationPoint(-3F, 17F, -1F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 20);
      Shape4.addBox(0F, 0F, 0F, 0, 1, 1);
      Shape4.setRotationPoint(-2F, 15F, -1F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 18);
      Shape5.addBox(0F, -1F, 0F, 1, 0, 1);
      Shape5.setRotationPoint(-2F, 16F, -1F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 20);
      Shape6.addBox(0F, 0F, 0F, 0, 1, 1);
      Shape6.setRotationPoint(-1F, 14F, -1F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 22);
      Shape7.addBox(0F, -1F, 0F, 1, 0, 1);
      Shape7.setRotationPoint(-3F, 17F, -1.2F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    torso.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    torso2.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
    leg1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    leg2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    leg1.rotateAngleY = 0.0F;
    leg2.rotateAngleY = 0.0F;
    {
        leg1.rotationPointZ = -1.0F;
        leg2.rotationPointZ = -1.0F;
        leg1.rotationPointY = 22F;
        leg2.rotationPointY = 22F;
    }
  }

}