// Date: 8/12/2012 10:10:34 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelpancake extends ModelBase
{
  //fields
    ModelRenderer torso;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer torso2;
    ModelRenderer torso2;
    ModelRenderer torso2;
    ModelRenderer torso2;
    ModelRenderer torso2;
    ModelRenderer torso2;
    ModelRenderer torso2;
    ModelRenderer torso2;
    ModelRenderer torso2;
  
  public Modelpancake()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      torso = new ModelRenderer(this, 0, 0);
      torso.addBox(-6F, -6F, 0F, 12, 12, 1);
      torso.setRotationPoint(0F, 16F, -1F);
      torso.setTextureSize(64, 32);
      torso.mirror = true;
      setRotation(torso, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 32, 0);
      leg1.addBox(-1F, 0F, 0F, 1, 2, 1);
      leg1.setRotationPoint(-3F, 22F, -1F);
      leg1.setTextureSize(64, 32);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 27, 0);
      leg2.addBox(0F, 0F, 0F, 1, 2, 1);
      leg2.setRotationPoint(3F, 22F, -1F);
      leg2.setTextureSize(64, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 17);
      torso2.addBox(-1F, -1F, -1F, 2, 2, 1);
      torso2.setRotationPoint(-4.033333F, 20F, -0.2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 22);
      torso2.addBox(-1F, -1F, -1F, 2, 2, 1);
      torso2.setRotationPoint(3.966667F, 12F, -0.2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 17);
      torso2.addBox(-1F, -1F, -1F, 2, 2, 1);
      torso2.setRotationPoint(3.966667F, 20F, -0.2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 17);
      torso2.addBox(-1F, -1F, -1F, 2, 2, 1);
      torso2.setRotationPoint(3.966667F, 16F, -0.2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 17);
      torso2.addBox(-1F, -1F, -1F, 2, 2, 1);
      torso2.setRotationPoint(-0.03333334F, 16F, -0.2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 17);
      torso2.addBox(-1F, -1F, -1F, 2, 2, 1);
      torso2.setRotationPoint(-0.03333334F, 20F, -0.2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 17);
      torso2.addBox(-1F, -1F, -1F, 2, 2, 1);
      torso2.setRotationPoint(-0.03333334F, 12F, -0.2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 27);
      torso2.addBox(-1F, -1F, -1F, 2, 2, 1);
      torso2.setRotationPoint(-4.033333F, 12F, -0.2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 17);
      torso2.addBox(-1F, -1F, -1F, 2, 2, 1);
      torso2.setRotationPoint(-4.033333F, 16F, -0.2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    torso.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    torso2.render(f5);
    torso2.render(f5);
    torso2.render(f5);
    torso2.render(f5);
    torso2.render(f5);
    torso2.render(f5);
    torso2.render(f5);
    torso2.render(f5);
    torso2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
