// Date: 8/22/2012 6:37:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modlepanb extends ModelBase
{
  //fields
    ModelRenderer torso;
    ModelRenderer torso2;
  
  public Modlepanb()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      torso = new ModelRenderer(this, 0, 0);
      torso.addBox(-4F, -4F, 0F, 8, 8, 1);
      torso.setRotationPoint(0F, 23F, 0F);
      torso.setTextureSize(64, 32);
      torso.mirror = true;
      setRotation(torso, -1.570796F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 10);
      torso2.addBox(-3F, -3F, -1F, 6, 6, 1);
      torso2.setRotationPoint(-0.03333334F, 23.8F, 0F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, -1.570796F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    torso.render(f5);
    torso2.render(f5);
  }
  public void renderModel(float f5){
      torso.render(f5);
      torso2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
