// Date: 8/8/2012 12:24:09 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelpancake extends ModelBase
{
  //fields
    ModelRenderer torso;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer torso2;
  
  public Modelpancake()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      torso = new ModelRenderer(this, 0, 0);
      torso.addBox(-3F, -6F, 0F, 8, 8, 1);
      torso.setRotationPoint(-1F, 22F, -1F);
      torso.setTextureSize(64, 32);
      torso.mirror = true;
      setRotation(torso, -1.570796F, 0F, 0F);
      leg1 = new ModelRenderer(this, 24, 0);
      leg1.addBox(0F, 0F, 0F, 1, 2, 1);
      leg1.setRotationPoint(-2F, 22F, -4F);
      leg1.setTextureSize(64, 32);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 19, 0);
      leg2.addBox(0F, 0F, 0F, 1, 2, 1);
      leg2.setRotationPoint(1F, 22F, -4F);
      leg2.setTextureSize(64, 32);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      torso2 = new ModelRenderer(this, 0, 10);
      torso2.addBox(-2F, -2F, -1F, 6, 6, 1);
      torso2.setRotationPoint(-1.033333F, 22.8F, 2F);
      torso2.setTextureSize(64, 32);
      torso2.mirror = true;
      setRotation(torso2, -1.570796F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    torso.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    torso2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
